### ISSUE TITLE
seems like this is what we are looking for

### ISSUE THREAD

**Issue by obastemur** [thlorenz/nad#6]
Embedding native addon into core is highly needed especially when 
- cross compiling for another platform. 
- targeting a platform that has no compiler facility to install a native module (iOS)

We target mobile and embedded platforms with JXcore, and such facility is needed prior to release.

I was planning a toolkit that runs prior to 'configure' and embeds given modules into core build. This approach fails for some uses cases though. i.e. module depends on c++ exceptions. Compiling the addon as a static-library might cover some of these issues but there are others to deal with.

Leaving the edge cases aside, it's still useful to have such a tool. Would you consider extending this work to handle pre-configure stuff (cross-platform) or do you have some bottle-necks in mind ?

**Comment by thlorenz** [comment]
I'm open to PRs that add this feature as long as existing ones don't break.
However I'm personally not able to spend time on that.

Closing this issue, but looking forward to PR :)
